import 'package:flutter/material.dart';

import '../../constant/drawer.dart';
import '../../constant/menuButton.dart';

class Kingdom extends StatelessWidget {
  const Kingdom({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.black,
        drawer: DrawerExtends(),
        appBar: AppBar(
          title: Text("Kingdom of God"),
          backgroundColor: Colors.black,
        ),
        body: Center(
          child: SingleChildScrollView(
            child: Column(
              children: [
                Container(
                  padding: EdgeInsets.all(5),
                  child: Image.asset(
                    'assets/come.jpg',
                  ),
                ),
                SizedBox(
                  height: 10,
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Message(
                    """
The terms kingdom of God and kingdom of heaven are frequently found in Holy Scripture and in contemporary Christian usage.
The primary meaning of kingdom is the authority, reign, or rule of a king. The territory, subjects, and operations of the kingdom are secondary meanings. The concept of a Kingdom of God is not primarily one of space, territory, or politics, as in a national kingdom, but instead, one of kingly rule, reign, and sovereign control.  The Kingdom of God is the realm where God reigns supreme, and Jesus Christ is King. In this kingdom, God’s authority is recognized, and his will is obeyed. 
""",
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Message(
                      """The kingdom of God is the sphere of God’s rule (Psalm 22:28). Though rightfully under God’s rule, fallen human beings nonetheless participate in universal rebellion against God and His authority (1 John 5:19; Revelation 11:17,18). However, by faith and obedience men and women turn from their rebellion, are regenerated by the Holy Spirit, and become a part of the Kingdom and its operation. While participation in the kingdom of God is not compulsory, the Kingdom is present, whether or not people recognize and accept it.

                    """),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Message(
                      '''The Kingdom is variously described as “kingdom of heaven” (Matthew 13:11), “kingdom of God” (Mark 4:11), “kingdom of Christ and of God” (Ephesians 5:5), and “kingdom of our Lord and of his Christ” (Revelation 11:15). Jesus sometimes spoke of it as “my kingdom” (Luke 22:30). Paul, referring to Christ Jesus, called it “his kingdom” (2 Timothy 4:1). All these terms refer to the one kingdom of God.

                    '''),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Message(
                      '''From the various contexts of the word kingdom in the Gospels, the rule of God is seen as (1) a present realm or sphere into which people are entering now and (2) a future apocalyptic order into which the righteous will enter at the end of the age. Thus the kingdom of God is both a present reality and a promise of future fulfillment. The Kingdom was present on earth in the person and acts of Jesus during the time of His Incarnation. After the Resurrection, the Risen Christ is present by His Spirit, and where His Spirit is, the Kingdom is present. While the Kingdom is manifested in the Church, the Kingdom is not limited to the Church. The fullness of the kingdom awaits a final apocalyptic arrival at the end of this age (Matthew 24:27,30,31; Luke 21:27–31).

                    '''),
                ),
                Container(
                  padding: EdgeInsets.all(5),
                  child: Image.asset(
                    'assets/kingdom2.jpg',
                  ),
                ),
                SizedBox(
                  height: 20,
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Message(
                      '''Christ taught His disciples to pray, “Your kingdom come” (Matthew 6:10). The Kingdom is already among us in that it has invaded Satan’s domain and has assured final victory. The Kingdom comes in a measure whenever a person receives Christ as Savior, is healed or delivered, or is touched in any way by the divine. Yet the future consummation of the kingdom of God—the time when all evil and rebellion will be eliminated—is the fervent hope of the Christian. So with the disciples we pray, “Your kingdom come”—both now and when Christ returns.
The rapture of the Church, the coming of Christ for His own, will set in motion the events that lead to the consummation of the eternal Kingdom. “The kingdom of the world has become the kingdom of our Lord and of his Christ, and he will reign for ever and ever” (Revelation 11:15).

                    '''),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Message(
                      '''To summarize, the Kingdom of God is the realm where Jesus Christ reigns as King and God’s authority is supreme. This Kingdom exists here and now (in part) in the lives and hearts of the redeemed, as well as in perfection and fullness in the future.
                    '''),
                ),
                RoundedButton(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  text: "back to home",
                  color: Colors.green,
                ),
              ],
            ),
          ),
        ));
  }
}

class Message extends StatelessWidget {
  Message(@required this.message);
  String message;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.all(11),
      child: Expanded(
        child: Text(
          message,
          style: TextStyle(
            color: Colors.white,
            fontSize: 16,
          ),
        ),
      ),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(13),
        color: Colors.deepPurple,
      ),
    );
  }
}
